# Generated by Django 3.1.5 on 2021-01-10 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_place_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='occupied',
            field=models.BooleanField(default=False, verbose_name='Занято ли'),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(default=datetime.date(2021, 1, 10), verbose_name='Дата для бронирования'),
        ),
    ]
