# Generated by Django 3.1.5 on 2021-01-10 17:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0006_auto_20210110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 10), null=True, verbose_name='Дата для бронирования'),
        ),
    ]
