# Generated by Django 3.1.5 on 2021-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20210110_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['office'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AddField(
            model_name='place',
            name='view',
            field=models.CharField(default=0, editable=False, max_length=100, verbose_name='Место'),
            preserve_default=False,
        ),
    ]
