# Generated by Django 3.1.5 on 2021-01-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20210110_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 11), null=True, verbose_name='Дата для бронирования'),
        ),
        migrations.AlterField(
            model_name='place',
            name='view',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Место'),
        ),
    ]
