# Generated by Django 3.1.5 on 2021-01-11 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20210111_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='count_of_free_places',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест'))], verbose_name='Кол-во свободных мест'),
        ),
        migrations.AlterField(
            model_name='office',
            name='count_of_occupied_places',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест'))], verbose_name='Кол-во занятых мест'),
        ),
        migrations.AlterField(
            model_name='office',
            name='count_of_places',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест'),
        ),
    ]
