# Generated by Django 3.1.5 on 2021-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_auto_20210111_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='hide_count_of_free_places',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='hide_count_of_occupied_places',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='hide_count_of_places',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
