# Generated by Django 3.1.5 on 2021-01-12 10:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0014_auto_20210111_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='count_of_free_places',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Кол-во свободных мест'),
        ),
        migrations.AlterField(
            model_name='office',
            name='count_of_occupied_places',
            field=models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест'))], verbose_name='Кол-во занятых мест'),
        ),
        migrations.AlterField(
            model_name='office',
            name='count_of_places',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест'),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 12), null=True, verbose_name='Дата для бронирования'),
        ),
    ]
