# Generated by Django 3.1.5 on 2021-01-12 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_auto_20210112_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={},
        ),
        migrations.RemoveField(
            model_name='office',
            name='count_of_free_places',
        ),
        migrations.RemoveField(
            model_name='office',
            name='count_of_occupied_places',
        ),
        migrations.RemoveField(
            model_name='office',
            name='count_of_places',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Номер кабинета')),
                ('count_of_places', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест')),
                ('count_of_occupied_places', models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во мест'))], verbose_name='Кол-во занятых мест')),
                ('count_of_free_places', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Кол-во свободных мест')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='office.office')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='office.room'),
            preserve_default=False,
        ),
    ]
