# Generated by Django 3.1.5 on 2021-01-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_auto_20210112_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['address'], 'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['room'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='office',
        ),
        migrations.AlterField(
            model_name='place',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='office.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='office.office'),
        ),
    ]
