# Generated by Django 3.1.5 on 2021-01-15 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_auto_20210112_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 16), null=True, verbose_name='Дата для бронирования'),
        ),
    ]
