# Generated by Django 3.1.5 on 2021-01-16 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0018_auto_20210115_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='first_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Первая дата'),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 17), null=True, verbose_name='Дата для бронирования'),
        ),
    ]
