# Generated by Django 3.1.5 on 2021-01-18 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_auto_20210116_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес офиса'),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 19), null=True, verbose_name='Зарезервированная дата'),
        ),
        migrations.AlterField(
            model_name='place',
            name='first_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Первая дата'),
        ),
    ]
