# Generated by Django 3.1.5 on 2021-01-20 22:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0020_auto_20210118_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['office'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 22), null=True, verbose_name='Зарезервированная дата'),
        ),
        migrations.AlterField(
            model_name='place',
            name='first_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 21), editable=False, null=True, verbose_name='Первая дата'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'office')},
        ),
        migrations.CreateModel(
            name='UsersPreviousPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Дата начала бронирования')),
                ('last_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Дата окончания бронирования')),
                ('client', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_previous_place', to=settings.AUTH_USER_MODEL)),
                ('offices', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.office', verbose_name='Офисы')),
                ('places', models.ManyToManyField(blank=True, editable=False, null=True, to='office.Place', verbose_name='Места')),
                ('rooms', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='office.room', verbose_name='Кабинеты')),
            ],
            options={
                'verbose_name': 'Бывшее место пользователей',
                'verbose_name_plural': 'Бывшие места пользователей',
            },
        ),
    ]
