# Generated by Django 3.1.5 on 2021-01-25 16:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0021_auto_20210121_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 26), null=True, verbose_name='Зарезервированная дата'),
        ),
        migrations.AlterField(
            model_name='place',
            name='first_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 1, 25), editable=False, null=True, verbose_name='Первая дата'),
        ),
    ]
