# Generated by Django 3.1.5 on 2021-01-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0022_auto_20210125_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspreviousplace',
            name='places',
        ),
    ]
