# Generated by Django 3.1.5 on 2021-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0023_remove_userspreviousplace_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspreviousplace',
            name='place',
            field=models.CharField(default=None, editable=False, max_length=150, verbose_name='Место'),
            preserve_default=False,
        ),
    ]
