# Generated by Django 3.1.5 on 2021-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0025_userspreviousplace_office_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspreviousplace',
            old_name='office_name',
            new_name='office',
        ),
        migrations.RemoveField(
            model_name='userspreviousplace',
            name='offices',
        ),
        migrations.RemoveField(
            model_name='userspreviousplace',
            name='rooms',
        ),
        migrations.AddField(
            model_name='userspreviousplace',
            name='room',
            field=models.CharField(default=None, editable=False, max_length=150, verbose_name='Кабинет'),
            preserve_default=False,
        ),
    ]
